server:
  port: 8330

spring:
  application:
    name: ZUUL-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8120/eureka

# prefix是uri前缀，带上
zuul:
  prefix: /api
  routes:
    CONSUMER-WEB: /product/**
    SERVICE-HELLO: /hello/**

management:
  security:
    enabled: false
