server:
  port: 8330

spring:
  application:
    name: ZUUL-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8120/eureka

zuul:
  routes:
    CONSUMER-WEB: /product/**
    hello:
      path: /hello/**
      service-id: service-hello